org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

archives_base_name=default-server-listings
mod_id=default_server_listings
mod_version=1.x-DEV-SNAPSHOT
maven_group=dev.matthiesen
mod_name=Default Server Listings
mod_description=Simple client side mod that adds default server list entries to the server-list.
mod_license=MIT License
mod_license_url=https://github.com/Matthiesen-dev/default-server-listings/blob/main/LICENSE
mod_author=Adam Matthiesen
mod_author_id=adammatthiesen
mod_author_url=https://github.com/Adammatthiesen
github_url=https://github.com/Matthiesen-dev/default-server-listings
git_url=github.com/Matthiesen-dev/default-server-listings
modrinth_url=https://modrinth.com/mod/default-server-listings

# Used for prism deployment, not consumed by build-logic
minecraft_version=1.21.1